# result_dir = '../result/1st_try/{now_str}'
preprocess_dir_name = '1st_try'
model_type = 'LightGBM'
result_dir = '../result/1st_try_LightGBM_test'
seed = 3655
n_iter = 20000

[preprocess_params]
preprocessed_dir_name = '1st_try'
n_splits = 5

[train_params]
learning_rate = 0.01
objective= 'binary'
metric = 'cross_entropy'
verbosity = -1



[test_params]
